# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: serviceConnection
    type: string
    default: 'AzureRmPipeline-conn-aaa'
  
steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: ${{ parameters.serviceConnection }}
    subscriptionId: '0117d21b-998a-4874-938f-becdcb5db055'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'azure-devops-testing'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/playerdn/azure-arm-cd/main/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName xtdevops'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
